using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;

public class BeeperClass : MonoBehaviour
{
    [SerializeField] GameManager gameManager;
    [SerializeField] HBHClass hbh;
    [SerializeField] BeeroidClass beeroids;

    StoreItemClass beepers = new StoreItemClass();
    StoreItemClass beeped = new StoreItemClass();
    StoreItemClass pickInterval = new StoreItemClass();

    float beepTimer;
    
    [SerializeField] GameObject beeperMan;


    // Start is called before the first frame update
    void Start()
    {
        // beekeepers
        beepers.SetUpgrade(0, 0, 1.0f);
        beepers.SetCost(50.0f, 50.0f, 1.2f);

        // number of new bees generated by beekeepers, efficiency upgrade
        beeped.SetUpgrade(1, 1, 1.1f);
        beeped.SetCost(50.0f, 50.0f, 1.2f);

        // timer keeping track of beekeeper interval
        beepTimer = 0.0f;

        // interval at which beekeepers generate new bees
        pickInterval.SetUpgrade(5.0f, 5.0f, 0.98f);
        pickInterval.SetCost(60.0f, 60.0f, 1.25f);

    }

    // Update is called once per frame
    void Update()
    {
        // compare beekeeper timer to the interval
        // if its time to trigger the beekeeper bee generation, trigger that and reset timer
        beepTimer += Time.deltaTime;
        if (beepTimer > pickInterval.upgradeF)
        {
            triggerBeep();
            beepTimer = 0.0f;
        }
    }


    // BEEKEEPER UPGRADES //////////////////////////////////////////////////////////////////////////////////
    // creates a new beekeeper
    public void AddBeeper()
    {
        // increase number of beekeepers
        beepers.upgradeI++;
        Instantiate(beeperMan, new Vector3(0.0f, -4.5f, 0.0f), Quaternion.identity);
        Debug.Log("created beeper");
    }

    // upgrades beekeeper efficiency
    public void BeeperEfficiency()
    {
        // increase beeped var based on beepedMult var
        beeped.upgradeI = (int)Mathf.Ceil(beeped.upgradeI * beeped.upgradeMult);
        Debug.Log("beeped var = " + beeped);

        // increase beepCost based on beepCostMult
        beeped.cost = beeped.cost * beeped.costMult;
    }

    // upgrades beekeeper interval
    public void BeeperInterval()
    {
        // lower pickInterval based on pickIntMult
        if (pickInterval.upgradeF > 0.5f)
        {
            pickInterval.upgradeF = pickInterval.upgradeF * pickInterval.upgradeMult;

            // force it to 2 decimal places
            float remainder = (pickInterval.upgradeF % 0.01f);
            pickInterval.upgradeF = remainder >= 0.005f ? pickInterval.upgradeF + (0.01f - remainder) : pickInterval.upgradeF - remainder;
        }

        // cap pickInterval upgrades to beekeepers triggering once every 0.5 seconds
        else if (pickInterval.upgradeF < 0.5f)
        {
            pickInterval.upgradeF = 0.5f;

            // TO-DO: lock the pickInterval upgrade button
            // might be able to do through storeItemClass?
        }

        Debug.Log("pick interval = " + pickInterval.upgradeF);

        // increase pickIntCost based on pickIntCostMult
        //pickIntCost = pickIntCost * pickIntCostMult;
        pickInterval.Purchase();
    }


    // HELPER FUNCTIONS ////////////////////////////////////////////////////////////////////////////////////
    // auto click trigger; generates more bees
    public void triggerBeep()
    {
        int numBeeps;
        numBeeps = beeped.upgradeI * beepers.upgradeI;

        if (gameManager.hbhActive == true)
        {
            numBeeps = (int)(numBeeps * hbh.effic);
        }
        else if (gameManager.beeroidsActive == true)
        {
            numBeeps = (int)(numBeeps * beeroids.effic);
        }

        gameManager.totalBees += numBeeps;
        Debug.Log("bees generated: " + numBeeps);

        // display text
        gameManager.beeCountText.text = "total bees: " + gameManager.totalBees;
    }
}
